export const GET_PRODUCTS = 'GET_PRODUCTS';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const CHOOSE_PRODUCT = 'CHOOSE_PRODUCT';
export const REMOVE_PRODUCT_REQUEST = 'REMOVE_PRODUCT_REQUEST';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const UPDATE_CART_PRODUCT = 'UPDATE_CART_PRODUCT';

export const CLOSE_MODAL = 'CLOSE_MODAL';
export const TOGGLE_CART_MODAL = 'TOGGLE_CART_MODAL';

export const INCREMENT_COUNTER_REQUEST = 'INCREMENT_COUNTER_REQUEST';
export const DECREMENT_COUNTER_REQUEST = 'DECREMENT_COUNTER_REQUEST';
export const UPDATE_COUNTER_REQUEST = 'UPDATE_COUNTER_REQUEST';
export const UPDATE_COUNTER_SUCCESS = 'UPDATE_COUNTER_SUCCESS';

export const SEARCH_PRODUCT_REQUEST = 'SEARCH_PRODUCT_REQUEST';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
