export const GET_PRODUCTS_SAGA = 'GET_PRODUCTS_SAGA';
export const SET_PRODUCTS_SAGA = 'LOAD_PRODUCTS_SAGA';
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const UPDATE_PRODUCT_AMOUNT = 'UPDATE_PRODUCT_AMOUNT';
